# Generated by Django 4.2.16 on 2026-06-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('template', models.CharField(choices=[('elegant', 'Elegant Gold'), ('floral', 'Floral Botanical')], default='elegant', max_length=30)),
                ('groom_name', models.CharField(max_length=120)),
                ('groom_full_name', models.CharField(blank=True, max_length=200)),
                ('groom_father', models.CharField(blank=True, max_length=200)),
                ('groom_mother', models.CharField(blank=True, max_length=200)),
                ('groom_order', models.CharField(blank=True, help_text='Putra ke- dari ...', max_length=120)),
                ('groom_photo', models.URLField(blank=True)),
                ('groom_instagram', models.CharField(blank=True, max_length=120)),
                ('bride_name', models.CharField(max_length=120)),
                ('bride_full_name', models.CharField(blank=True, max_length=200)),
                ('bride_father', models.CharField(blank=True, max_length=200)),
                ('bride_mother', models.CharField(blank=True, max_length=200)),
                ('bride_order', models.CharField(blank=True, help_text='Putri ke- dari ...', max_length=120)),
                ('bride_photo', models.URLField(blank=True)),
                ('bride_instagram', models.CharField(blank=True, max_length=120)),
                ('cover_photo', models.URLField(blank=True)),
                ('main_date', models.DateField(blank=True, null=True)),
                ('quote', models.TextField(blank=True)),
                ('quote_source', models.CharField(blank=True, max_length=200)),
                ('music_url', models.URLField(blank=True)),
                ('opening_text', models.TextField(blank=True, default='Tanpa mengurangi rasa hormat, kami mengundang Bapak/Ibu/Saudara/i untuk hadir di acara pernikahan kami.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='invitations.invitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('attendance', models.CharField(choices=[('yes', 'Hadir'), ('no', 'Tidak Hadir'), ('maybe', 'Masih Ragu')], default='yes', max_length=10)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='invitations.invitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoveStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_label', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_story', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_address', models.TextField(blank=True)),
                ('maps_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=120)),
                ('account_holder', models.CharField(max_length=200)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='invitations.invitation')),
            ],
        ),
    ]
