# Generated by Django 4.2.16 on 2026-06-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Nama/keterangan foto (opsional)', max_length=200)),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Galeri Upload Foto',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
