# Generated by Django 4.2.16 on 2026-06-12 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_count', models.PositiveIntegerField(help_text='Jumlah link undangan yang diaktifkan', unique=True)),
                ('price', models.DecimalField(decimal_places=0, help_text='Harga dalam Rupiah', max_digits=12)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paket Harga',
                'verbose_name_plural': 'Paket Harga',
                'ordering': ['link_count'],
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Undangan hanya bisa dibuka publik setelah dipublikasikan (dibayar).'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_count', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('cancelled', 'Dibatalkan')], default='pending', max_length=12)),
                ('payment_method', models.CharField(blank=True, max_length=60)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invitations', models.ManyToManyField(blank=True, related_name='orders', to='invitations.invitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Pesanan',
                'ordering': ['-created_at'],
            },
        ),
    ]
