# Generated by Django 4.2.16 on 2026-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_pricingtier_invitation_is_published_invitation_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='closing_text',
            field=models.TextField(blank=True, default='Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir dan memberikan doa restu.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='dresscode',
            field=models.CharField(blank=True, help_text='Contoh: Earth tone / Formal', max_length=200),
        ),
        migrations.AddField(
            model_name='invitation',
            name='dresscode_colors',
            field=models.CharField(blank=True, help_text='Daftar warna dipisah koma, contoh: #c9a063,#6a6253,#ffffff', max_length=200),
        ),
        migrations.AddField(
            model_name='invitation',
            name='gift_address',
            field=models.TextField(blank=True, help_text='Alamat pengiriman kado/hadiah fisik (opsional)'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='live_stream_url',
            field=models.URLField(blank=True, help_text='Tautan live streaming acara (YouTube/Zoom/IG)'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='wedding_hashtag',
            field=models.CharField(blank=True, help_text='Contoh: #DimasRinaForever', max_length=80),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='template',
            field=models.CharField(choices=[('elegant', 'Elegant Gold'), ('floral', 'Floral Botanical'), ('luxury', 'Luxury Dark Gold'), ('modern', 'Modern Minimalist')], default='elegant', max_length=30),
        ),
    ]
