# Generated by Django 4.2.16 on 2026-06-12 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitation_closing_text_invitation_dresscode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='preview_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_countdown',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Hitung Mundur'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_couple',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Mempelai'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_events',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Acara'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_gallery',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Galeri'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_gift',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Wedding Gift'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_guestbook',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Buku Tamu'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_info',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Info Tambahan'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_love_story',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Love Story'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_quote',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Quote/Ayat'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='show_rsvp',
            field=models.BooleanField(default=True, verbose_name='Tampilkan RSVP'),
        ),
    ]
