# Generated by Django 4.2.16 on 2026-06-12 11:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0005_invitation_preview_token_invitation_show_countdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Nama/judul lagu (opsional)', max_length=200)),
                ('audio', models.FileField(upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a', 'ogg', 'wav'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musik',
                'verbose_name_plural': 'Galeri Upload Musik',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
