# Generated by Django 4.2.16 on 2026-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_audiotrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qris_image', models.ImageField(blank=True, help_text='Upload gambar QRIS. Akan ditampilkan ke pembeli saat pembayaran.', upload_to='payment/')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Nomor WhatsApp untuk konfirmasi (format 62..., contoh: 6281917190895)', max_length=30)),
                ('account_info', models.TextField(blank=True, help_text='Info rekening/transfer alternatif (opsional).')),
                ('instructions', models.TextField(blank=True, default='Scan QRIS di atas untuk membayar, lalu konfirmasi pembayaran dan kirim bukti transfer ke WhatsApp kami. Akun Anda akan diaktifkan setelah pembayaran diverifikasi.', help_text='Instruksi pembayaran yang ditampilkan ke pembeli.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Pembayaran',
                'verbose_name_plural': 'Pengaturan Pembayaran',
            },
        ),
    ]
