# Generated by Django 4.2.16 on 2026-06-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_alter_invitation_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='template',
            field=models.CharField(choices=[('elegant', 'Elegant Gold'), ('floral', 'Floral Botanical'), ('luxury', 'Luxury Dark Gold'), ('modern', 'Modern Minimalist'), ('aurora', 'Aurora Glass'), ('royal', 'Royal Vintage')], default='elegant', max_length=30),
        ),
    ]
